version: 1
docker: bootstrap
release: core-build-out
# forced-release-3:core-build-out
schema: publication
github-actions: publication
# forced-github-actions-6:publication
add-vitest-coverage-acro: maintenance
run: publication
# forced-run-9:publication
# forced-run-10:publication
app: publication
